In [215]:
import numpy as np
import pandas as pd

def fatorarGS(n, A):
    Q = np.copy(A) #inicializa Q como uma copia de A
    R = np.zeros((n,n))
    normas = [] #cria um vetor que armazena as normas das bases ortogonais
    for j in range(n):
        normas.append(np.sqrt(Q[:,j].dot(Q[:,j])))
        print(np.sqrt(Q[:,j].dot(Q[:,j])))
        for i in range(n):
            for k in range(j):
                print(Q[i][j])
                print(Q[i][k])
                Q[i][j] = float(Q[i][j] - Q[i][k]/(normas[k])) #remove as projecoes do vetor com relacao as outras bases ortogonais
                print(Q[i][j])
                print(Q[i][k])
                print("------")
    
    print(normas)
    print(Q)
        
    return Q,R

In [216]:
A = [[1.,1.,0.],[0.,1.,1.], [1.,0.,1.]]
Q,R = fatorarGS(3,A)

1.4142135623730951
1.4142135623730951
1.0
1.0
0.29289321881345254
1.0
------
1.0
0.0
1.0
0.0
------
0.0
1.0
-0.7071067811865475
1.0
------
1.4142135623730951
0.0
1.0
-0.7071067811865475
1.0
------
-0.7071067811865475
0.29289321881345254
-0.914213562373095
0.29289321881345254
------
1.0
0.0
1.0
0.0
------
1.0
1.0
0.29289321881345254
1.0
------
1.0
1.0
0.29289321881345254
1.0
------
0.29289321881345254
-0.7071067811865475
0.7928932188134525
-0.7071067811865475
------
[1.4142135623730951, 1.4142135623730951, 1.4142135623730951]
[[ 1.          0.29289322 -0.91421356]
 [ 0.          1.          0.29289322]
 [ 1.         -0.70710678  0.79289322]]


In [200]:
print (1)

1


In [217]:
A = [[12,-51,4],[6,167,-68],[-4,24,-41]]
Q,R = fatorarGS(3,A)



14.0
176.2554963681984
-51
12
-51
12
------
167
6
166
6
------
24
-4
24
-4
------
79.50471684120383
4
12
3
12
------
3
-51
3
-51
------
-68
6
-68
6
------
-68
166
-68
166
------
-41
-4
-40
-4
------
-40
24
-40
24
------
[14.0, 176.2554963681984, 79.50471684120383]
[[ 12 -51   3]
 [  6 166 -68]
 [ -4  24 -40]]
